{
    'name': 'Dimofinf cPanel Manager',
    'version': '1.0',
    'author': 'Dimofinf',
    'category': 'Tools',
    'summary': 'Full cPanel API Integration for Hosting Management',
    'description': 'Provides comprehensive management for servers, accounts, packages, databases, emails, DNS, and more.',
    'depends': ['base', 'mail'],
    'data': [
        'views/cpanel_domain_views.xml',
        'views/report_accounts_by_server.xml',
        'views/cpanel_server_accounts_view.xml',
        'views/dashboard_view.xml',
        'views/cpanel_file_views.xml',
        'views/cpanel_backup_views.xml',
        'data/email_templates.xml',
        'views/cpanel_server_views.xml',
        'views/cpanel_account_views.xml',
        'views/cpanel_package_views.xml',
        'views/cpanel_database_views.xml',
        'views/cpanel_dns_views.xml',
        'data/cron_jobs.xml',
        'views/report_accounts_by_server.xml',
    ],
    'application': True,
    'license': 'LGPL-3',
}